### ISSUE TITLE
[Issue] The code can't build with Spin 0.8.0，Can update it?

### ISSUE THREAD

**Issue by lshoo** [fermyon/cloud-start#10]
Hi,
I installed the Spin 0.8.0 on Ubuntu 22.04.01 and clone this code.
When I run `spin build`，get lots of errors (can't found rust std).

**Comment by karthik2804** [comment]
Do you have rust installed? `spin build` uses the rust toolchain to build the app. You can find instructions on installing the rust toolchain [here](https://www.rust-lang.org/tools/install)

**Comment by lshoo** [comment]
> Do you have rust installed? `spin build` uses the rust toolchain to build the app. You can find instructions on installing the rust toolchain [here](https://www.rust-lang.org/tools/install)

I have installed rust 1.67.0 and cargo 1.25.1

**Comment by karthik2804** [comment]
Make sure to add the `wasm32-wasi` target with 

```
rustup target add wasm32-wasi
``

**Comment by lshoo** [comment]
Thanks, It works
